name: build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install command dependencies
        run: |
          echo "::set-env name=GO_VERSION::$(go version | awk '{ print $3}' | sed 's/^go//')"

      - name: Lint
        run: make lint

      - name: Build
        run: make build-client

      - name: Release(test)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
