name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0
      - uses: azure/setup-kubectl@v1
        name: Install kubectl
      - name: Test
        run: kubectl get ns
