name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare env
        run: echo "GO_VERSION=$(go version | awk '{ print $3}' | sed 's/^go//')" >> $GITHUB_ENV

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Test coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: make build-cli
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0
      - name: Test CLI
        run: |
          ./bin/k3ai-cli apply argo --kubectl
          kubectl get po

      - name: Release(test)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
