name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
